services:
  app-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/app-db-password
      POSTGRES_DB: pagila
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - ./compose/app-db/docker-entrypoint-initdb.d/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./compose/app-db/docker-entrypoint-initdb.d/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
    ports:
      - 5432:5432
    secrets:
      - app-db-password

  analytics-dwh:
    image: clickhouse/clickhouse-server:24.6
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: $ANALYTICS_DWH_USER
      CLICKHOUSE_PASSWORD: $ANALYTICS_DWH_PASSWORD
    volumes:
      - ./compose/analytics-dwh/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - analytics-dwh-data:/var/lib/clickhouse
      - analytics-dwh-logs:/var/log/clickhouse-server
    ports:
      - 18123:8123
      - 19000:9000

  dagster-db:
    image: postgres:13
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD_FILE: /run/secrets/dagster-db-password
      POSTGRES_DB: dagster
    volumes:
      - dagster-db-data:/var/lib/postgresql/data
    secrets:
      - dagster-db-password

  metabase-db:
    image: postgres:13
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/metabase-db-password
      POSTGRES_DB: metabase
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    secrets:
      - metabase-db-password

  dagster-daemon:
    image: sakila-company/dagster
    build:
      context: ./sakila_etl
      dockerfile: Dockerfile_base
    pull_policy: never
    entrypoint: ["dagster-daemon", "run", "-w", "workspace.yaml"]
    environment:
      DAGSTER_DB_USERNAME: dagster
      DAGSTER_DB_PASSWORD: $DAGSTER_DB_PASSWORD
    volumes:
      - ./compose/dagster/dagster.yaml:/opt/dagster/dagster.yaml
      - ./compose/dagster/workspace.yaml:/opt/dagster/workspace.yaml
    depends_on:
      - dagster-db

  dagster-webserver:
    image: sakila-company/dagster
    build:
      context: ./sakila_etl
      dockerfile: Dockerfile_base
    pull_policy: never
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    environment:
      DAGSTER_DB_USERNAME: dagster
      DAGSTER_DB_PASSWORD: $DAGSTER_DB_PASSWORD
    volumes:
      - ./compose/dagster/dagster.yaml:/opt/dagster/dagster.yaml
      - ./compose/dagster/workspace.yaml:/opt/dagster/workspace.yaml
    ports:
      - 3000:3000
    depends_on:
      - dagster-db

  dagster-code-sakila_etl:
    image: sakila-company/dagster-worker
    build:
      context: ./sakila_etl
      dockerfile: Dockerfile
    pull_policy: never
    entrypoint:
      - "dagster"
      - "api"
      - "grpc"
      - "-h"
      - "0.0.0.0"
      - "-p"
      - "4000"
      - "-m"
      - "sakila_etl"
    environment:
      DAGSTER_DB_USERNAME: dagster
      DAGSTER_DB_PASSWORD: $DAGSTER_DB_PASSWORD
      DBT_PROFILES_DIR: /run/secrets/dbt
      DLT_SECRETS_DIR: /run/secrets/dlt
      DESTINATION__FILESYSTEM__BUCKET_URL: "data/dlt"
      DESTINATION__FILESYSTEM__KWARGS: '{"auto_mkdir": true}'
    volumes:
      - dagster-logs-data:/opt/dagster/logs
      - bucket-data:/opt/dagster/data
    secrets:
      - source: dagster-dbt-profiles
        target: /run/secrets/dbt/profiles.yml
      - source: dagster-dlt-secrets
        target: /run/secrets/dlt/secrets.toml
    depends_on:
      - dagster-db
      - app-db # Required for loading dlt source assets

  metabase:
    image: metabase/metabase:v0.50.21
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./compose/metabase/plugins/clickhouse.jar:/plugins/clickhouse.jar:ro
    ports:
      - 3100:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS_FILE: /run/secrets/metabase-db-password
      MB_DB_HOST: metabase-db
    secrets:
      - metabase-db-password
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabase-db

volumes:
  bucket-data:
  app-db-data:
  analytics-dwh-data:
  analytics-dwh-logs:
  dagster-db-data:
  metabase-db-data:
  dagster-logs-data:
  dagster-history-data:
  dagster-schedules-data:
  dagster-storage-data:

secrets:
  app-db-password:
    file: ./compose/app-db/secrets/db_password.txt
  dagster-db-password:
    file: ./compose/dagster-db/secrets/db_password.txt
  metabase-db-password:
    file: ./compose/metabase-db/secrets/db_password.txt
  dagster-dbt-profiles:
    file: ./compose/dagster/secrets/dbt_profiles.yml
  dagster-dlt-secrets:
    file: ./compose/dagster/secrets/dlt_secrets.toml
